version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=marvins4r
      - POSTGRES_DATABASE=pizza_shop_db
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
